version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - public/build/*
    - public/index.html
    - public/favicon.ico
    - public/logo192.png
    - public/manifest.json
    - public/robot.txt